
spring:
 profiles:
   active: dev
 datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
     username: root
     password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true


